/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Tone = IDL.Record({
  'isAnnoyed' : IDL.Bool,
  'isWarm' : IDL.Bool,
  'isRuleFocused' : IDL.Bool,
});
export const Request = IDL.Record({ 'text' : IDL.Text, 'intendedTone' : Tone });
export const Response = IDL.Record({ 'text' : IDL.Text, 'actualTone' : Tone });

export const idlService = IDL.Service({
  'askCharacter' : IDL.Func([Request], [Response], []),
  'clearHistory' : IDL.Func([], [], []),
  'getHistory' : IDL.Func([], [IDL.Vec(Response)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Tone = IDL.Record({
    'isAnnoyed' : IDL.Bool,
    'isWarm' : IDL.Bool,
    'isRuleFocused' : IDL.Bool,
  });
  const Request = IDL.Record({ 'text' : IDL.Text, 'intendedTone' : Tone });
  const Response = IDL.Record({ 'text' : IDL.Text, 'actualTone' : Tone });
  
  return IDL.Service({
    'askCharacter' : IDL.Func([Request], [Response], []),
    'clearHistory' : IDL.Func([], [], []),
    'getHistory' : IDL.Func([], [IDL.Vec(Response)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };